# Generated by Django 3.2.3 on 2021-05-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
