# Generated by Django 3.2.3 on 2021-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedelivery', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='battery_consumption_perKM_perHr',
            field=models.FloatField(default=0.0002),
        ),
        migrations.AddField(
            model_name='drone',
            name='number',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='drone',
            name='takeoff_landing_consumption',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.FloatField(default=10),
        ),
    ]
