# Generated by Django 3.2.3 on 2021-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedelivery', '0003_auto_20210529_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='battery_consumption_perKM_perHr',
        ),
        migrations.AddField(
            model_name='drone',
            name='battery_consumption_perKM_perKg',
            field=models.FloatField(default=2e-06),
        ),
    ]
