# Generated by Django 3.2.3 on 2021-05-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedelivery', '0004_auto_20210529_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(default='', max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
            ],
        ),
    ]
